#' Add new flag columns to variant and coverage tables
#'
#' @export
#' @param mdlvalr_list A standard `mdlvalr_list` object (as generated by `get_stats()`).
#' The class of this object can be used to automatically determine which
#' function methods will be used.
#' @param pipeline Standard name of the pipeline from which the data were derived.
#' @param cds_table A tibble object that contains the RefSeq CDS info. See also [add_cds_column()].
#' @param var_pass_fail_logic A logic statement that can be applied to the variant input table, such that TRUE returns a "pass" and FALSE returns a "fail" character string. Default is "TRUE", resulting in all variants getting a "pass" label.
#' @param cov_pass_fail_logic A logic statement that can be applied to the coverage input table, such that TRUE returns a "pass" and FALSE returns a "fail" character string. Default is "TRUE", resulting in all variants getting a "pass" label.
#'
#' @section Methods:
#' This function is a **generic**, which means that different
#' implementations (methods) can be executed for different classes. The class
#' of the first argument will determine which method is used. See the documentation of
#' individual methods for extra arguments and differences in behaviour.
#'
#' @return Returns a standard `mdlvalr_list` object (i.e. a regular R list of lists) that contains tables as named list elements. 
#' The class of the retuned object is updated to include the name of the pipeline. This facilitates use of alternative methods in 
#' downstream functions. 
#'
#' @examples
#' class(mdlvalr_list)
#' # [1] "hybcap" "list"
#' \notrun{
#' mdlvalr_list <- add_flags(mdlvalr_list,
#'     cds_table,
#'     var_pass_fail_logic = "VAF >= 0.05",
#'     cov_pass_fail_logic = "fraction_125x >= 0.9")
#'}
#'
add_flags <- function(mdlvalr_list, 
        pipeline = NULL,
        cds_table = NULL,
        var_pass_fail_logic = "TRUE", 
        cov_pass_fail_logic = "TRUE") {
    UseMethod("add_flags")
}


#' @export
#' @rdname add_flags
add_flags.hybcap <- function(mdlvalr_list, 
        pipeline = "hybcap",
        cds_table = NULL,
        var_pass_fail_logic = "TRUE", 
        cov_pass_fail_logic = "TRUE") {
    for (i in seq_along(names(mdlvalr_list$comparisons))) {
        # Add some helpful flag columns to indicate common VAF thresholds
        var_1 <- mdlvalr_list$comparisons[[i]]$input_data$var_1 %>%
            dplyr::mutate(vaf_gt_0.03 = if_else(VAF >= 0.03, "yes", "no")) %>%
            dplyr::mutate(vaf_gt_0.05 = if_else(VAF >= 0.05, "yes", "no"))
        var_2 <- mdlvalr_list$comparisons[[i]]$input_data$var_2 %>%
            dplyr::mutate(vaf_gt_0.03 = if_else(VAF >= 0.03, "yes", "no")) %>%
            dplyr::mutate(vaf_gt_0.05 = if_else(VAF >= 0.05, "yes", "no"))
                
        if (!is.null(cds_table)) {
            var_1 <- add_cds_column(var_1, cds_table)
            var_2 <- add_cds_column(var_2, cds_table)
        }
        
        # Add some helpful flag columns to indicate common coverage metrics
        cov_1 <- mdlvalr_list$comparisons[[i]]$input_data$cov_1 %>%
            dplyr::mutate(fraction_125x_gt_0.9 = if_else(fraction_125x >= 0.9, "yes", "no"))
            
        cov_2 <- mdlvalr_list$comparisons[[i]]$input_data$cov_2 %>%
            dplyr::mutate(fraction_125x_gt_0.9 = if_else(fraction_125x >= 0.9, "yes", "no"))
        
        # Add variant table pass/fail flag column depending on input logic
        var_1 <- var_1 %>%
            dplyr::mutate(var_pass_fail = case_when(
                eval(parse(text = var_pass_fail_logic)) ~ "pass",
                TRUE ~ "fail"
                ))
        var_2 <- var_2 %>%
            dplyr::mutate(var_pass_fail = case_when(
                eval(parse(text = var_pass_fail_logic)) ~ "pass",
                TRUE ~ "fail"
                ))
        # Add coverage table pass/fail flag column depending on input logic
        cov_1 <- cov_1 %>%
            dplyr::mutate(cov_pass_fail = case_when(
                eval(parse(text = cov_pass_fail_logic)) ~ "pass",
                TRUE ~ "fail"
                ))
        cov_2 <- cov_2 %>%
            dplyr::mutate(cov_pass_fail = case_when(
                eval(parse(text = cov_pass_fail_logic)) ~ "pass",
                TRUE ~ "fail"
                ))

        mdlvalr_list$comparisons[[i]]$flagged_data <- list(
            var_1 = var_1,
            var_2 = var_2,
            cov_1 = cov_1,
            cov_2 = cov_2
        )
    } 
    class(mdlvalr_list) <- class(mdlvalr_list)
    return(mdlvalr_list)
}






#' Add a within CDS flag column to var table
#' 
#' Add a column to a variant table that indicates whether the start position of the variant is within a refseq CDS region. 
#' @export
#' @param var_tbl Tibble of variants. Must have columns named: "chr", "start", and "end". Must not have a column named "type", as that is the column being joined from the `cds_table`.
#' @param cds_table Tibble RefSeq gff that includes CDS regions. Must have column name: "chr", "start", "end", and "type" that indicates the CDS or not.
#'
#' @return Returns the same var_tbl that was input, but includes additional column named "within_refseq_cds" to indicate the variant start position overlaps with a CDS region.
add_cds_column <- function(var_tbl, cds_table) {
    cds_table_granges <- cds_table %>%
        dplyr::select(chr, start, end, type) %>%
        dplyr::mutate(start = as.numeric(start)) %>%
        dplyr::mutate(end = as.numeric(end)) %>%
        dplyr::rename(seqnames = "chr") %>%
        dplyr::relocate(seqnames) %>%
        dplyr::mutate(seqnames = glue("chr{seqnames}")) %>%
        plyranges::as_granges()

    var_tbl_granges <- var_tbl %>%
        dplyr::mutate(start = as.numeric(POS)) %>%
        dplyr::mutate(end = as.numeric(POS)) %>%
        dplyr::mutate(seqnames = CHROM) %>%
        dplyr::relocate(seqnames) %>%
        plyranges::as_granges()

    var_tbl_granges_cds <- plyranges::join_overlap_left(var_tbl_granges, cds_table_granges) %>%
        as_tibble() %>%
        distinct() %>%
        dplyr::select(-seqnames, -start, -end, -width, -strand) %>%
        dplyr::rename(within_refseq_cds = "type") %>%
        dplyr::mutate(within_refseq_cds = if_else(is.na(within_refseq_cds), "no", "yes"))
    return(var_tbl_granges_cds)
}
