#' Add columns to compared data that labels variants into groups
#'
#' @export
#' @param mdlvalr_list A standard `mdlvalr_list` object (as generated by `compare_data()`).
#' The class of this object can be used to automatically determine which
#' function methods will be used.
#' @param pipeline Standard name of the pipeline from which the data were derived.
#'
#' @section Methods:
#' This function is a **generic**, which means that different
#' implementations (methods) can be executed for different classes. The class
#' of the first argument will determine which method is used. See the documentation of
#' individual methods for extra arguments and differences in behaviour.
#'
#' @return Returns a standard `mdlvalr_list` object (i.e. a regular R list of lists) that contains tables as named list elements. 
#' The class of the retuned object is updated to include the name of the pipeline. This facilitates use of alternative methods in 
#' downstream functions. 
#'
#' @examples
#' \dontrun{
#' class(mdlvalr_list)
#' # [1] "hybcap" "list"
#' mdlvalr_list <- add_var_labels(
#'     mdlvalr_list,
#'     pipeline = "hybcap")
#'}
add_var_labels <- function(mdlvalr_list, pipeline = NULL) {
    UseMethod("add_var_labels")
}




#' @export
#' @rdname add_var_labels
add_var_labels.hybcap <- function(
    mdlvalr_list,
    pipeline = "hybcap") {
    for (i in seq_along(names(mdlvalr_list$comparisons))) {
        full_join <- mdlvalr_list$comparisons[[i]]$compared_data$full_join %>%
            dplyr::mutate(vars_in_common_s1pass_s2pass = case_when(
                var_pass_fail.sample1 == "pass" & var_pass_fail.sample2 == "pass" ~ "yes",
                TRUE ~ "no"
                )) %>%
            dplyr::mutate(vars_in_common_s1pass_s2fail = case_when(
                var_pass_fail.sample1 == "pass" & var_pass_fail.sample2 == "fail" ~ "yes",
                TRUE ~ "no"
                )) %>%
            dplyr::mutate(vars_in_common_s1fail_s2pass = case_when(
                var_pass_fail.sample1 == "fail" & var_pass_fail.sample2 == "pass" ~ "yes",
                TRUE ~ "no"
                )) %>%
            dplyr::mutate(vars_in_common_s1fail_s2fail = case_when(
                var_pass_fail.sample1 == "fail" & var_pass_fail.sample2 == "fail" ~ "yes",
                TRUE ~ "no"
                ))

        vars_in_common <- mdlvalr_list$comparisons[[i]]$compared_data$vars_in_common %>%
            dplyr::mutate(vars_in_common_s1pass_s2pass = case_when(
                var_pass_fail.sample1 == "pass" & var_pass_fail.sample2 == "pass" ~ "yes",
                TRUE ~ "no"
                )) %>%
            dplyr::mutate(vars_in_common_s1pass_s2fail = case_when(
                var_pass_fail.sample1 == "pass" & var_pass_fail.sample2 == "fail" ~ "yes",
                TRUE ~ "no"
                )) %>%
            dplyr::mutate(vars_in_common_s1fail_s2pass = case_when(
                var_pass_fail.sample1 == "fail" & var_pass_fail.sample2 == "pass" ~ "yes",
                TRUE ~ "no"
                )) %>%
            dplyr::mutate(vars_in_common_s1fail_s2fail = case_when(
                var_pass_fail.sample1 == "fail" & var_pass_fail.sample2 == "fail" ~ "yes",
                TRUE ~ "no"
                ))

        vars_in_s1_not_in_s2  <- mdlvalr_list$comparisons[[i]]$compared_data$vars_in_s1_not_in_s2 %>%
            dplyr::mutate(vars_in_s1pass_not_in_s2 = case_when(
                var_pass_fail == "pass" ~ "yes",
                TRUE ~ "no"
                )) %>%
            dplyr::mutate(vars_in_s1fail_not_in_s2 = case_when(
                var_pass_fail == "fail" ~ "yes",
                TRUE ~ "no"
                ))

        vars_in_s2_not_in_s1  <- mdlvalr_list$comparisons[[i]]$compared_data$vars_in_s2_not_in_s1 %>%
            dplyr::mutate(vars_in_s2pass_not_in_s1 = case_when(
                var_pass_fail == "pass" ~ "yes",
                TRUE ~ "no"
                )) %>%
            dplyr::mutate(vars_in_s2fail_not_in_s1 = case_when(
                var_pass_fail == "fail" ~ "yes",
                TRUE ~ "no"
                ))

        mdlvalr_list$comparisons[[i]]$labeled_data <- list(
            full_join = full_join,
            vars_in_common = vars_in_common,
            vars_in_s1_not_in_s2 = vars_in_s1_not_in_s2,
            vars_in_s2_not_in_s1 = vars_in_s2_not_in_s1
        )
    } 
    class(mdlvalr_list) <- class(mdlvalr_list)
    return(mdlvalr_list)
}

