#' Write Excel files containing all sumarized data within tabs
#'
#' @export
#' @param mdlvalr_list A standard `mdlvalr_list` object (as generated by `compare_data()`).
#' The class of this object can be used to automatically determine which
#' function methods will be used.
#' @param pipeline Standard name of the pipeline from which the data were derived.
#' @param filename_prefix String or filepath that will be glued as a prefix to the output filename.
#'
#' @section Methods:
#' This function is a **generic**, which means that different
#' implementations (methods) can be executed for different classes. The class
#' of the first argument will determine which method is used. See the documentation of
#' individual methods for extra arguments and differences in behaviour.
#'
#' @return Returns a standard `mdlvalr_list` object (i.e. a regular R list of lists) that contains tables as named list elements. 
#' The class of the retuned object is updated to include the name of the pipeline. This facilitates use of alternative methods in 
#' downstream functions. 
#'
#' @examples
#' class(mdlvalr_list)
#' # [1] "hybcap" "list"
#' \notrun{
#' mdlvalr_list <- export_excel(
#'     mdlvalr_list,
#'     pipeline = "hybcap",
#'     filename_prefix = "logic_VAF_gt_0.05_")
#'}
export_excel <- function(
    mdlvalr_list,
    pipeline = NULL,
    filename_prefix = "") {
    UseMethod("export_excel")
}




#' Export data to Excel files using tabs
#'
#'
#'
#' @export
#' @rdname export_excel
export_excel.hybcap <- function(
    mdlvalr_list,
    pipeline = "hybcap",
    filename_prefix = "") {
    for (i in seq_along(names(mdlvalr_list$comparisons))) {
        curr_comparison <- names(mdlvalr_list$comparisons)[i]

        flagged_names <- names(mdlvalr_list$comparisons[[i]]$flagged_data)
        flagged <- mdlvalr_list$comparisons[[i]]$flagged_data
        filtered_names <- names(mdlvalr_list$comparisons[[i]]$filtered_data)
        filtered <- mdlvalr_list$comparisons[[i]]$filtered_data
        compared_names <- names(mdlvalr_list$comparisons[[i]]$compared_data)
        compared <- mdlvalr_list$comparisons[[i]]$compared_data
        labeled_names <- names(mdlvalr_list$comparisons[[i]]$labeled_data)
        labeled <- mdlvalr_list$comparisons[[i]]$labeled_data
        summary_tbl <- mdlvalr_list$comparisons[[i]]$summary %>%
              bind_rows()

        out_list <- c(list(summary = summary_tbl), flagged, labeled, filtered)
        wb <- write.xlsx(out_list, file = glue("{filename_prefix}{curr_comparison}.xlsx"), overwrite = TRUE)
    }
    wb <- write.xlsx(list(all_samples = mdlvalr_list$summary), file = glue("{filename_prefix}all.xlsx"), overwrite = TRUE)
}

