#' Filter compared data into sub-tables based on vairant labels
#'
#' @export
#' @param mdlvalr_list A standard `mdlvalr_list` object (as generated by `add_var_labels()`).
#' The class of this object can be used to automatically determine which
#' function methods will be used.
#' @param pipeline Standard name of the pipeline from which the data were derived.
#'
#' @section Methods:
#' This function is a **generic**, which means that different
#' implementations (methods) can be executed for different classes. The class
#' of the first argument will determine which method is used. See the documentation of
#' individual methods for extra arguments and differences in behaviour.
#'
#' @return Returns a standard `mdlvalr_list` object (i.e. a regular R list of lists) that contains tables as named list elements. 
#' The class of the retuned object is updated to include the name of the pipeline. This facilitates use of alternative methods in 
#' downstream functions. 
#'
#' @examples
#' class(mdlvalr_list)
#' # [1] "hybcap" "list"
#' \notrun{
#' mdlvalr_list <- filter_data(
#'     mdlvalr_list,
#'     pipeline = "hybcap")
#'}
filter_data <- function(mdlvalr_list, pipeline = NULL) {
    UseMethod("filter_data")
}




#' @export
#' @rdname filter_data
filter_data.hybcap <- function(
    mdlvalr_list,
    pipeline = "hybcap") {

    for (i in seq_along(names(mdlvalr_list$comparisons))) {
        # Samples that pass
        vars_in_s1pass <- mdlvalr_list$comparisons[[i]]$flagged_data$var_1 %>%
            dplyr::filter(var_pass_fail == "pass")
        vars_in_s2pass <- mdlvalr_list$comparisons[[i]]$flagged_data$var_2 %>%
            dplyr::filter(var_pass_fail == "pass")


        # Vars common to both samples
        vars_in_common_s1pass_s2pass <- mdlvalr_list$comparisons[[i]]$labeled_data$vars_in_common %>%
            dplyr::filter(vars_in_common_s1pass_s2pass == "yes")
        vars_in_common_s1pass_s2fail <- mdlvalr_list$comparisons[[i]]$labeled_data$vars_in_common %>%
            dplyr::filter(vars_in_common_s1pass_s2fail == "yes")
        vars_in_common_s1fail_s2pass <- mdlvalr_list$comparisons[[i]]$labeled_data$vars_in_common %>%
            dplyr::filter(vars_in_common_s1fail_s2pass == "yes")
        vars_in_common_s1fail_s2fail <- mdlvalr_list$comparisons[[i]]$labeled_data$vars_in_common %>%
            dplyr::filter(vars_in_common_s1fail_s2fail == "yes")


        # Vars in one sample but not the other
        vars_in_s1pass_not_in_s2 <- mdlvalr_list$comparisons[[i]]$labeled_data$vars_in_s1_not_in_s2 %>%
            dplyr::filter(vars_in_s1pass_not_in_s2 == "yes")
        vars_in_s1fail_not_in_s2 <- mdlvalr_list$comparisons[[i]]$labeled_data$vars_in_s1_not_in_s2 %>%
            dplyr::filter(vars_in_s1fail_not_in_s2 == "yes")

        vars_in_s2pass_not_in_s1 <- mdlvalr_list$comparisons[[i]]$labeled_data$vars_in_s2_not_in_s1 %>%
            dplyr::filter(vars_in_s2pass_not_in_s1 == "yes")
        vars_in_s2fail_not_in_s1 <- mdlvalr_list$comparisons[[i]]$labeled_data$vars_in_s2_not_in_s1 %>%
            dplyr::filter(vars_in_s2fail_not_in_s1 == "yes")


        exons_in_s1pass <- mdlvalr_list$comparisons[[i]]$flagged_data$cov_1 %>%
            dplyr::filter(cov_pass_fail == "pass")
        exons_in_s2pass <- mdlvalr_list$comparisons[[i]]$flagged_data$cov_2 %>%
            dplyr::filter(cov_pass_fail == "pass")
        exons_in_s1fail <- mdlvalr_list$comparisons[[i]]$flagged_data$cov_1 %>%
            dplyr::filter(cov_pass_fail == "fail")
        exons_in_s2fail <- mdlvalr_list$comparisons[[i]]$flagged_data$cov_2 %>%
            dplyr::filter(cov_pass_fail == "fail")


        mdlvalr_list$comparisons[[i]]$filtered_data <- list(
            vars_in_s1pass = vars_in_s1pass,
            vars_in_s2pass = vars_in_s2pass,
            vars_in_common_s1pass_s2pass = vars_in_common_s1pass_s2pass,
            vars_in_common_s1pass_s2fail = vars_in_common_s1pass_s2fail,
            vars_in_common_s1fail_s2pass = vars_in_common_s1fail_s2pass,
            vars_in_common_s1fail_s2fail = vars_in_common_s1fail_s2fail,
            vars_in_s1pass_not_in_s2 = vars_in_s1pass_not_in_s2,
            vars_in_s1fail_not_in_s2 = vars_in_s1fail_not_in_s2,
            vars_in_s2pass_not_in_s1 = vars_in_s2pass_not_in_s1,
            vars_in_s2fail_not_in_s1 = vars_in_s2fail_not_in_s1,
            exons_in_s1pass = exons_in_s1pass,
            exons_in_s2pass = exons_in_s2pass,
            exons_in_s1fail = exons_in_s1fail,
            exons_in_s2fail = exons_in_s2fail 
        )
    } 
    class(mdlvalr_list) <- class(mdlvalr_list)
    return(mdlvalr_list)
}

