#' Calculate summary statistics of concordance tables
#'
#' @export
#' @param mdlvalr_list A standard `mdlvalr_list` object (as generated by `get_stats()`).
#' The class of this object can be used to automatically determine which
#' function methods will be used.
#' @param pipeline Standard name of the pipeline from which the data were derived.
#'
#' @section Methods:
#' This function is a **generic**, which means that different
#' implementations (methods) can be executed for different classes. The class
#' of the first argument will determine which method is used. See the documentation of
#' individual methods for extra arguments and differences in behaviour.
#'
#' @return Returns a standard `mdlvalr_list` object (i.e. a regular R list of lists) that contains tables as named list elements. 
#' The class of the retuned object is updated to include the name of the pipeline. This facilitates use of alternative methods in 
#' downstream functions. 
#'
#' @examples
#' \dontrun{
#' class(mdlvalr_list)
#' # [1] "hybcap" "list"
#' 
#' mdlvalr_list <- get_stats(mdlvalr_list)
#'}
get_stats <- function(mdlvalr_list, pipeline = NULL) {
    UseMethod("get_stats")
}




#' @export
#' @rdname get_stats
get_stats.hybcap <- function(mdlvalr_list, pipeline = "hybcap") {
    for (i in seq_along(names(mdlvalr_list$comparisons))) {
        # Samples
        comparison_name <- names(mdlvalr_list$comparisons)[i]
        s1_name <- mdlvalr_list$sample_sheet %>% 
            dplyr::slice(i) %>%
            dplyr::pull(comparison_name_1)
        s2_name <- mdlvalr_list$sample_sheet %>% 
            dplyr::slice(i) %>%
            dplyr::pull(comparison_name_2)

        # Vars in each sample
        n_vars_in_s1 <- mdlvalr_list$comparisons[[i]]$flagged_data$var_1 %>%
            nrow()
        n_vars_in_s2 <- mdlvalr_list$comparisons[[i]]$flagged_data$var_2 %>%
            nrow()
        n_vars_in_s1pass <- mdlvalr_list$comparisons[[i]]$filtered_data$vars_in_s1pass %>%
            nrow()
        n_vars_in_s2pass <- mdlvalr_list$comparisons[[i]]$filtered_data$vars_in_s2pass %>%
            nrow()

        # Vars common to both samples
        n_vars_in_common <- mdlvalr_list$comparisons[[i]]$labeled_data$vars_in_common %>%
            nrow()
        n_vars_in_common_s1pass_s2pass <- mdlvalr_list$comparisons[[i]]$filtered_data$vars_in_common_s1pass_s2pass %>%
            nrow()
        n_vars_in_common_s1pass_s2fail <- mdlvalr_list$comparisons[[i]]$filtered_data$vars_in_common_s1pass_s2fail %>%
            nrow()
        n_vars_in_common_s1fail_s2pass <- mdlvalr_list$comparisons[[i]]$filtered_data$vars_in_common_s1fail_s2pass %>%
            nrow()
        n_vars_in_common_s1fail_s2fail <- mdlvalr_list$comparisons[[i]]$filtered_data$vars_in_common_s1fail_s2fail %>%
            nrow()

        # Vars in one sample but not the other
        n_vars_in_s1_not_in_s2 <- mdlvalr_list$comparisons[[i]]$labeled_data$vars_in_s1_not_in_s2 %>%
            nrow()
        n_vars_in_s1pass_not_in_s2 <- mdlvalr_list$comparisons[[i]]$filtered_data$vars_in_s1pass_not_in_s2 %>%
            nrow()
        n_vars_in_s1pass_in_cds_not_in_s2 <- mdlvalr_list$comparisons[[i]]$filtered_data$vars_in_s1pass_in_cds_not_in_s2 %>%
            nrow()
        n_vars_in_s1fail_not_in_s2 <- mdlvalr_list$comparisons[[i]]$filtered_data$vars_in_s1fail_not_in_s2 %>%
            nrow()

        n_vars_in_s2_not_in_s1 <- mdlvalr_list$comparisons[[i]]$labeled_data$vars_in_s2_not_in_s1 %>%
            nrow()
        n_vars_in_s2pass_not_in_s1 <- mdlvalr_list$comparisons[[i]]$filtered_data$vars_in_s2pass_not_in_s1 %>%
            nrow()
        n_vars_in_s2pass_in_cds_not_in_s1 <- mdlvalr_list$comparisons[[i]]$filtered_data$vars_in_s2pass_in_cds_not_in_s1 %>%
            nrow()
        n_vars_in_s2fail_not_in_s1 <- mdlvalr_list$comparisons[[i]]$filtered_data$vars_in_s2fail_not_in_s1 %>%
            nrow()


        # Coverage data
        n_exons_in_s1 <- mdlvalr_list$comparisons[[i]]$flagged_data$cov_1 %>%
            nrow()
        n_exons_in_s2 <- mdlvalr_list$comparisons[[i]]$flagged_data$cov_2 %>%
            nrow()
        n_exons_in_s1pass <- mdlvalr_list$comparisons[[i]]$filtered_data$exons_in_s1pass %>%
            nrow()
        n_exons_in_s2pass <- mdlvalr_list$comparisons[[i]]$filtered_data$exons_in_s2pass %>%
            nrow()
        n_exons_in_s1fail <- mdlvalr_list$comparisons[[i]]$filtered_data$exons_in_s1fail %>%
            nrow()
        n_exons_in_s2fail <- mdlvalr_list$comparisons[[i]]$filtered_data$exons_in_s2fail %>%
            nrow()
        
        # Number of vars in common divided by all possible variants. Include vars that pass in only one sample.
        frac_concordance_raw <- format(round(
                n_vars_in_common_s1pass_s2pass /
                (sum(n_vars_in_common_s1pass_s2pass,
                     n_vars_in_common_s1pass_s2fail,
                     n_vars_in_common_s1fail_s2pass,
                     n_vars_in_s1pass_not_in_s2,
                     n_vars_in_s2pass_not_in_s1)
                ),
            3), nsmall = 2)
        # Number of vars in common divided by all possible variants. Do not include vars that pass in only one sample.
        frac_concordance_threshold <- format(round(
                n_vars_in_common_s1pass_s2pass /
                (sum(n_vars_in_common_s1pass_s2pass,
                     n_vars_in_s1pass_not_in_s2,
                     n_vars_in_s2pass_not_in_s1)
                ),
            3), nsmall = 2)
        # Number of vars in common divided by all possible variants. Do not include vars that pass in only one sample.
        # Do not include variants found outside the CDS regions. 
        frac_concordance_corrected <- format(round(
                n_vars_in_common_s1pass_s2pass /
                (sum(n_vars_in_common_s1pass_s2pass,
                     n_vars_in_s1pass_in_cds_not_in_s2,
                     n_vars_in_s2pass_in_cds_not_in_s1)
                ),
            3), nsmall = 2)
        frac_discrep_threshold <- format(round(
                sum(n_vars_in_common_s1pass_s2fail,
                    n_vars_in_common_s1fail_s2pass) /
                sum(n_vars_in_s1pass_not_in_s2,
                    n_vars_in_s2pass_not_in_s1),
            3), nsmall = 2)
        frac_exons_fail_s1 <- format(round(
                n_exons_in_s1fail / n_exons_in_s1,
            3), nsmall = 2)
        frac_exons_fail_s2 <- format(round(
                n_exons_in_s2fail / n_exons_in_s2,
            3), nsmall = 2)


        mdlvalr_list$comparisons[[i]]$summary <- list(
            comparison_name = comparison_name,
            s1_name = s1_name,
            s2_name = s2_name,
            n_vars_in_s1 = n_vars_in_s1,
            n_vars_in_s2 = n_vars_in_s2,
            n_vars_in_s1pass = n_vars_in_s1pass,
            n_vars_in_s2pass = n_vars_in_s2pass,
            n_vars_in_common = n_vars_in_common,
            n_vars_in_common_s1pass_s2pass = n_vars_in_common_s1pass_s2pass,
            n_vars_in_common_s1pass_s2fail = n_vars_in_common_s1pass_s2fail,
            n_vars_in_common_s1fail_s2pass = n_vars_in_common_s1fail_s2pass,
            n_vars_in_common_s1fail_s2fail = n_vars_in_common_s1fail_s2fail,
            n_vars_in_s1_not_in_s2 = n_vars_in_s1_not_in_s2,
            n_vars_in_s1pass_not_in_s2 = n_vars_in_s1pass_not_in_s2,
            n_vars_in_s1pass_in_cds_not_in_s2 = n_vars_in_s1pass_in_cds_not_in_s2,
            n_vars_in_s1fail_not_in_s2 = n_vars_in_s1fail_not_in_s2,
            n_vars_in_s2_not_in_s1 = n_vars_in_s2_not_in_s1,
            n_vars_in_s2pass_not_in_s1 = n_vars_in_s2pass_not_in_s1,
            n_vars_in_s2pass_in_cds_not_in_s1 = n_vars_in_s2pass_in_cds_not_in_s1,
            n_vars_in_s2fail_not_in_s1 = n_vars_in_s2fail_not_in_s1,
            n_exons_in_s1 = n_exons_in_s1, 
            n_exons_in_s2 = n_exons_in_s2,
            n_exons_in_s1pass = n_exons_in_s1pass,
            n_exons_in_s2pass = n_exons_in_s2pass,
            n_exons_in_s1fail = n_exons_in_s1fail,
            n_exons_in_s2fail = n_exons_in_s2fail,
            frac_concordance_raw = frac_concordance_raw,
            frac_concordance_threshold = frac_concordance_threshold,
            frac_concordance_corrected = frac_concordance_corrected,
            frac_discrep_threshold = frac_discrep_threshold,
            frac_exons_fail_s1 = frac_exons_fail_s1,
            frac_exons_fail_s2 = frac_exons_fail_s2
        )
    }
    # Collapse all comparisons into a single summary table
    mdlvalr_list$summary <- lapply(mdlvalr_list$comparisons, FUN = function(x) {x$summary}) %>%
        bind_rows() 

    class(mdlvalr_list) <- class(mdlvalr_list)
    return(mdlvalr_list)
}

